"""
Orchestrator — Main LangGraph StateGraph for the multi-agent code review pipeline.

Pipeline:
  START → planner → coder → security_reviewer → tester → human_checkpoint → END

Conditional routing:
  - If any node sets status="failed" → route to error_handler → END
  - If security_review.passed=False AND iteration < max_iterations → retry coder
  - After tester → human_checkpoint (interrupt_before for human-in-the-loop)
  - After human approval → create_pr → END

Features:
  - Shared AgentState across all nodes
  - Retry logic (max 3 iterations) for security failures
  - Human-in-the-loop checkpoint with interrupt_before
  - Full latency + cost tracking
"""

from __future__ import annotations

import logging
import os
import time
import uuid
from typing import Any, Dict, Literal

from .state import AgentState, PROutput
from .planner import plan_node
from .coder import code_node
from .security_reviewer import security_review_node
from .tester import tester_node

logger = logging.getLogger(__name__)

# Try to import LangGraph; provide informative error if not installed
try:
    from langgraph.graph import StateGraph, END, START
    from langgraph.checkpoint.memory import MemorySaver
    LANGGRAPH_AVAILABLE = True
except ImportError:
    LANGGRAPH_AVAILABLE = False
    logger.warning(
        "LangGraph not installed. Install with: pip install langgraph\n"
        "The orchestrator will fall back to sequential execution mode."
    )

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")


# ---------------------------------------------------------------------------
# Additional Node Implementations
# ---------------------------------------------------------------------------

def human_checkpoint_node(state: AgentState) -> Dict[str, Any]:
    """
    Human-in-the-loop node.

    In LangGraph, this node is marked with interrupt_before, which pauses
    execution and waits for an external resume signal (e.g. API call or UI action).

    For the mock/sequential path, it auto-approves (simulating human approval).
    """
    logger.info("[HumanCheckpoint] Awaiting human review...")

    # In production: LangGraph will interrupt here and wait for:
    # graph.update_state(thread_id, {"human_approved": True})
    # For mock: we auto-approve
    auto_approve = os.getenv("AUTO_APPROVE_CHECKPOINT", "true").lower() == "true"

    return {
        "human_approved": auto_approve,
        "status": "running" if auto_approve else "awaiting_human",
        "messages": [{
            "node": "human_checkpoint",
            "status": "approved" if auto_approve else "waiting",
            "auto_approved": auto_approve,
        }],
    }


def create_pr_node(state: AgentState) -> Dict[str, Any]:
    """
    Creates a GitHub Pull Request via the GitHub REST API.

    Requires: GITHUB_TOKEN env var.
    Falls back to a mock PR URL if not configured.
    """
    start_ms = int(time.time() * 1000)
    logger.info(f"[CreatePR] Generating PR for {state.get('repository', 'unknown')}")

    plan = state.get("plan")
    code = state.get("code")
    tests = state.get("tests")
    security = state.get("security_review")

    # Build PR body
    vuln_summary = "✅ No critical issues found."
    if security and not security.passed:
        vuln_summary = f"⚠️ {len(security.vulnerabilities)} issue(s) found (review required)."

    pr_title = f"fix({state.get('issue_id', 'N/A')}): {plan.summary if plan else 'Auto-generated fix'}"
    branch_name = f"fix/{state.get('issue_id', uuid.uuid4().hex[:8]).lower().replace(' ', '-')}"

    pr_body = f"""## Summary
{plan.summary if plan else 'Auto-generated fix by EAIOC Multi-Agent System'}

## Root Cause
{plan.root_cause if plan else 'See attached code changes'}

## Changes Made
- **File**: `{code.filename if code else 'unknown'}`
- **Summary**: {code.diff_summary if code else 'N/A'}

## Security Review
{vuln_summary}
{chr(10).join(f'- {r}' for r in (security.recommendations if security else []))}

## Tests Generated
- **Test file**: `{tests.filename if tests else 'N/A'}`
- **Test count**: {tests.test_count if tests else 0}

## Agent Pipeline Metrics
- Latency: {sum(state.get('latency_ms', {}).values())}ms total
- Tokens used: {state.get('total_tokens_used', 0)}
- Cost: ${state.get('total_cost_usd', 0.0):.4f}

---
*Generated by EAIOC Multi-Agent Orchestrator — [View Pipeline](https://github.com/{state.get('repository', 'org/repo')})*
"""

    pr_output = PROutput(
        title=pr_title,
        body=pr_body,
        branch_name=branch_name,
        base_branch="main",
        labels=["agent-generated", "needs-review"],
    )

    # Try GitHub API
    pr_url = f"https://github.com/{state.get('repository', 'org/repo')}/pull/MOCK-{uuid.uuid4().hex[:6]}"
    if GITHUB_TOKEN and state.get("repository"):
        try:
            import httpx
            repo = state["repository"]
            resp = httpx.post(
                f"https://api.github.com/repos/{repo}/pulls",
                headers={
                    "Authorization": f"Bearer {GITHUB_TOKEN}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                json={
                    "title": pr_output.title,
                    "body": pr_output.body,
                    "head": pr_output.branch_name,
                    "base": pr_output.base_branch,
                    "labels": pr_output.labels,
                },
                timeout=30.0,
            )
            if resp.status_code in {200, 201}:
                pr_url = resp.json().get("html_url", pr_url)
                logger.info(f"[CreatePR] GitHub PR created: {pr_url}")
            else:
                logger.warning(f"[CreatePR] GitHub API returned {resp.status_code}: {resp.text[:200]}")
        except Exception as e:
            logger.warning(f"[CreatePR] GitHub API failed ({e}), using mock URL")

    elapsed = int(time.time() * 1000) - start_ms
    return {
        "pr": pr_output,
        "status": "completed",
        "messages": [{
            "node": "create_pr",
            "status": "success",
            "pr_url": pr_url,
            "pr_title": pr_output.title,
            "elapsed_ms": elapsed,
        }],
        "latency_ms": {**state.get("latency_ms", {}), "create_pr": elapsed},
    }


def error_handler_node(state: AgentState) -> Dict[str, Any]:
    """Handles pipeline failures by logging and marking status=failed."""
    logger.error(f"[ErrorHandler] Pipeline failed: {state.get('error', 'Unknown error')}")
    return {
        "status": "failed",
        "messages": [{
            "node": "error_handler",
            "status": "terminal",
            "error": state.get("error", "Unknown error"),
            "iteration": state.get("iteration", 0),
        }],
    }


# ---------------------------------------------------------------------------
# Routing Functions (LangGraph conditional edges)
# ---------------------------------------------------------------------------

def route_after_security(state: AgentState) -> Literal["tester", "coder", "error_handler"]:
    """
    After security review:
    - FAILED + retries left → send back to coder for a fix
    - FAILED + no retries → error
    - PASSED → proceed to tester
    """
    if state.get("status") == "failed":
        return "error_handler"

    security = state.get("security_review")
    iteration = state.get("iteration", 0)
    max_iter = state.get("max_iterations", 3)

    if security and not security.passed:
        if iteration < max_iter:
            logger.info(f"[Router] Security failed. Retrying coder (iteration {iteration + 1}/{max_iter})")
            return "coder"
        else:
            logger.warning("[Router] Security failed. Max retries reached → error")
            return "error_handler"

    return "tester"


def route_after_any(state: AgentState) -> Literal["__end__", "error_handler"]:
    """Generic check: if status is 'failed', go to error handler, else continue."""
    if state.get("status") == "failed":
        return "error_handler"
    return "__end__"


def route_after_human(state: AgentState) -> Literal["create_pr", "error_handler"]:
    """After human checkpoint: approved → create PR, rejected → error."""
    if state.get("human_approved"):
        return "create_pr"
    return "error_handler"


# ---------------------------------------------------------------------------
# Graph Builder
# ---------------------------------------------------------------------------

def build_graph():
    """
    Constructs and compiles the LangGraph StateGraph for the agent pipeline.

    Returns the compiled graph (or a FallbackOrchestrator if LangGraph not installed).
    """
    if not LANGGRAPH_AVAILABLE:
        logger.warning("LangGraph not available — returning FallbackOrchestrator")
        return FallbackOrchestrator()

    memory = MemorySaver()
    graph = StateGraph(AgentState)

    # Add nodes
    graph.add_node("planner", plan_node)
    graph.add_node("coder", code_node)
    graph.add_node("security_reviewer", security_review_node)
    graph.add_node("tester", tester_node)
    graph.add_node("human_checkpoint", human_checkpoint_node)
    graph.add_node("create_pr", create_pr_node)
    graph.add_node("error_handler", error_handler_node)

    # Add edges
    graph.add_edge(START, "planner")
    graph.add_edge("planner", "coder")
    graph.add_edge("coder", "security_reviewer")

    # Conditional routing after security review
    graph.add_conditional_edges(
        "security_reviewer",
        route_after_security,
        {
            "tester": "tester",
            "coder": "coder",         # retry loop
            "error_handler": "error_handler",
        }
    )

    graph.add_edge("tester", "human_checkpoint")

    # Conditional routing after human checkpoint
    graph.add_conditional_edges(
        "human_checkpoint",
        route_after_human,
        {
            "create_pr": "create_pr",
            "error_handler": "error_handler",
        }
    )

    graph.add_edge("create_pr", END)
    graph.add_edge("error_handler", END)

    # Compile with memory checkpointing (enables human-in-the-loop)
    compiled = graph.compile(
        checkpointer=memory,
        interrupt_before=["human_checkpoint"],  # Pause before human review
    )
    logger.info("LangGraph pipeline compiled successfully")
    return compiled


# ---------------------------------------------------------------------------
# Fallback Orchestrator (sequential execution without LangGraph)
# ---------------------------------------------------------------------------

class FallbackOrchestrator:
    """
    Sequential execution fallback when LangGraph is not installed.
    Runs the same nodes in order, providing identical output structure.
    """

    async def ainvoke(self, input_state: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        state: AgentState = {
            "run_id": input_state.get("run_id", str(uuid.uuid4())),
            "issue": input_state.get("issue", ""),
            "issue_id": input_state.get("issue_id", "GH-0"),
            "repository": input_state.get("repository", ""),
            "plan": None,
            "code": None,
            "security_review": None,
            "tests": None,
            "pr": None,
            "iteration": 0,
            "max_iterations": input_state.get("max_iterations", 3),
            "human_approved": False,
            "error": None,
            "status": "running",
            "messages": [],
            "total_tokens_used": 0,
            "total_cost_usd": 0.0,
            "latency_ms": {},
        }

        for node_fn in [plan_node, code_node, security_review_node, tester_node,
                        human_checkpoint_node, create_pr_node]:
            updates = node_fn(state)
            state.update(updates)
            # Merge messages (additive)
            if "messages" in updates:
                state["messages"] = state.get("messages", []) + updates["messages"]

            if state.get("status") == "failed":
                break

        return state

    def invoke(self, input_state: Dict[str, Any], config: Dict[str, Any] = None) -> Dict[str, Any]:
        import asyncio
        return asyncio.get_event_loop().run_until_complete(self.ainvoke(input_state, config))
